---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/fission/fission
    targetRevision: HEAD
    helm:
      releaseName: fission
      valuesObject:
        fission-all:
          routerServiceType: ClusterIP

  destination:
    server: "https://kubernetes.default.svc"
    namespace: fission
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: releasenotes
    value: https://github.com/fission/fission
  - name: values.yaml
    value: https://github.com/fission/fission-charts/blob/main/charts/fission-all/values.yaml
