---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sevaho/atrium
    path: deployments/drone/drone
    targetRevision: HEAD
    helm:
      releaseName: drone
      valuesObject:
        drone:
          env:
            DRONE_SERVER_HOST: ${DRONE_PUBLIC_HOST}
            DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
            DRONE_SERVER_PROTO: https
            DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
            DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
            DRONE_DEBUG: true

  destination:
    server: "https://kubernetes.default.svc"
    namespace: drone
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

  info:
  - name: values.yaml
    value: https://github.com/drone/charts/blob/master/charts/drone/values.yaml
